myapp/lessons/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, DateField, SelectField
from wtforms.validators import DataRequired
from wtforms.fields.html5 import DateField
from myapp.models import Lesson



class LessonForm(FlaskForm):
    # student = SelectField('Student', choices = [Student])
    student = StringField("Student")
    title = StringField('Title', validators=[DataRequired()])
    lessonDate = DateField('Date', format='%Y-%m-%d', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    subject = TextAreaField('Subject', validators=[DataRequired()])
    submit = SubmitField('Post')

myapp/lessons/views.py
from cgi import print_arguments
from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required
from myapp import db 
from myapp.models import Lesson
from myapp.lessons.forms import LessonForm
from myapp.models import User

lessons = Blueprint('lessons', __name__)

@lessons.route('/lessons/create', methods=['GET', 'POST'])
@login_required
def create_lesson():
    form = LessonForm()
    if form.validate_on_submit():
        lesson = Lesson(lessonDate=form.lessonDate.data, title=form.title.data, subject=form.subject.data, content=form.content.data, user_id=current_user.id, student=form.student.data)
        db.session.add(lesson)
        db.session.commit()
        flash('Lesson CREATED')
        print('LESSON CREATED')
        return redirect(url_for('users.lessons', username=current_user.username))
    return render_template('create_lesson.html', form=form)

@lessons.route('/<int:lesson_id>/delete',methods=['GET','POST'])
@login_required
def delete_lesson(lesson_id):

    lesson = Lesson.query.get_or_404(lesson_id)
    if lesson.author != current_user:
        abort(403)

    db.session.delete(lesson)
    db.session.commit()
    flash('Lesson Deleted')
    return redirect(url_for('users.lessons', username=current_user.username))    

@lessons.route('/<int:lesson_id>')
def lesson(lesson_id):
    lesson = Lesson.query.get_or_404(lesson_id) 
    return render_template('lesson.html', title=lesson.title, student=lesson.student, lessonDate=lesson.lessonDate, content=lesson.content, subject=lesson.subject, date=lesson.date, lesson=lesson)    

@lessons.route('/<int:lesson_id>/update',methods=['GET','POST'])
@login_required
def update(lesson_id):
    lesson = Lesson.query.get_or_404(lesson_id)

    if lesson.author != current_user:
        abort(403)

    form = LessonForm()

    if form.validate_on_submit():
        lesson.lessonDate = form.lessonDate.data
        lesson.title = form.title.data
        lesson.subject = form.subject.data
        lesson.content = form.content.data
        lesson.student = form.student.data
        db.session.commit()
        flash('Lesson Updated')
        return redirect(url_for('lessons.lesson',lesson_id=lesson.id))

    elif request.method == 'GET':
        form.lessonDate.data = lesson.lessonDate
        form.title.data = lesson.title
        form.subject.data = lesson.subject
        form.content.data = lesson.content
        form.content.data = lesson.content
        form.student.data = lesson.student
        

    return render_template('create_lesson.html',title='Updating',form=form)

@lessons.route('/lessons/<student_name>')
def student(student_name):
  page = request.args.get('page', 1, type=int)
  lessons = Lesson.query.filter_by(student=student_name).order_by(Lesson.lessonDate.desc()).paginate(page=page, per_page=5) 
  return render_template('student.html', student=student_name, lessons=lessons)

myapp/users/views.py
from crypt import methods
from operator import methodcaller
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from myapp import db
from myapp.models import User, Lesson
from myapp.users.forms import RegistrationForm, LoginForm, UpdateUserForm

users = Blueprint('users', __name__) # dont forget to register this in __init__.py 

@users.route('/<username>/lessons')
@login_required
def lessons(username):
  page = request.args.get('page', 1, type=int)
  user = User.query.filter_by(username=username).first_or_404()
  lessons = Lesson.query.filter_by(author=user).order_by(Lesson.lessonDate.desc()).paginate(page=page, per_page=5) 
  return render_template('lessons.html', lessons=lessons, user=user, username=username)

@users.route('/<username>/calendar')
@login_required
def calendar(username):
  page = request.args.get('page', 1, type=int)
  user = User.query.filter_by(username=username).first_or_404()
  lessons = Lesson.query.filter_by(author=user)
  return render_template('calendar.html', lessons=lessons, user=user, username=username)  

@users.route('/<username>/students')
@login_required
def students(username):
  page = request.args.get('page', 1, type=int)
  user = User.query.filter_by(username=username).first_or_404()
  lessons = Lesson.query.filter_by(author=user).distinct('student').paginate(page=page, per_page=5) 
  return render_template('some_students.html', lessons=lessons, user=user, username=username)  




# register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for Registration!')
        return redirect(url_for('users.login'))
    
    return render_template('register.html', form=form)

# login
@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)

# logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index')) #once the user has logged out we will redirect them back home


#account (update UserForm)
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit(): 
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User account updated!!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template('account.html', form=form)

myapp/templates/Students.html
{% extends "base.html" %}
{% block content %}

<main>
  
  {% for lesson in lessons.items %}
  <h1>
    <a href="{{ url_for('lessons.student', student_name=lesson.student) }}">
      {{lesson.student}} 
    </a>
  </h1>

  {% endfor %}
  <nav aria-label="Page Navigation example" class="pag-nav">
    <div class=pagination>
      {% for page_num in lessons.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if lessons.page == page_num %}
          <li class="page-item disabled">
              <a class="page-link" href="{{url_for('users.students', username=current_user.username, page=page_num)}}">{{ page_num }}</a>
          </li>
        {% else %}
          <li class="page-item">
              <a class="page-link" href="{{url_for('users.students', username=current_user.username, page=page_num)}}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}
    </div>
  </main>
  </nav>
</main>

{% endblock %}

myapp/templates/account.html
{% extends "base.html" %}
{% block content %}

<main>
<div >
    <div align="center">
        <h1>Welcome {{current_user.username}}</h1>
    </div>
</div>

<div class="container">
    <form method="POST" action="" enctype="multipart/form-data">
        <div class="form-group">
            {{form.hidden_tag()}}
        </div>
        <div class="form-group">
            {{form.username.label(class='form-group')}} 
            {{form.username(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.email.label(class='form-group')}} 
            {{form.email(class='form-control')}}
        </div>
      
        <div class="form-group">
            {{form.submit(class='btn btn-primary')}}
        </div>
       
       
    </form>
</div>
</main>
{% endblock %}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../static/css/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Schoolbell&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>Learnin'</title>
</head>
<body>
    <ul class="navbar navbar-dark bg-dark">
        {% if current_user.is_authenticated %}
         <li class="navbar-brand">
            <a href="{{url_for('users.lessons', username=current_user.username)}}">Home</a>
            {% else %}
            <li class="navbar-brand">
                <a href="{{url_for('users.register')}}">Home</a>
            </li>
            {% endif %}
        </li>
        
       

        {% if current_user.is_authenticated %}
        <span id="right-side-nav">
            <li class="nav-link">
                <a href="{{url_for('users.lessons', username=current_user.username)}}">My Lessons</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('users.students', username=current_user.username)}}">My Students</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('lessons.create_lesson')}}">Create Lesson</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('users.logout')}}">Log Out</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('users.account')}}">Update Account</a>
            </li>
            
            {% else %}
            <li class="nav-link">
                <a href="{{url_for('users.login')}}">Log In</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('users.register')}}">Register</a>
            </li>
        </span>
        {% endif %}
    </ul>

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

myapp/templates/calendar.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.0/main.min.css">
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.0/main.min.js"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='../static/css/calendar.css') }}">

<main>
 <h3><a href="{{url_for('users.lessons', username=current_user.username)}}">Switch to List</a></h3> 
  <div id="calendar">
  <script>
    let calendarEl = document.getElementById('calendar');

    let calendar = new FullCalendar.Calendar(calendarEl, {
      events : [
      {% for lesson in lessons %}

      {
        title: `{{lesson.student}}`,
        start: '{{lesson.lessonDate}}',
        eventClick: function (info) {
          alert('hi')
        }
      },
      
      {% endfor %}
      ],})

    calendar.render()
  </script>
  </div>
  {% for lesson in lessons.items %}
  <p id="lesson-summary">
    <a href="{{ url_for('lessons.student', student_name=lesson.student) }}">
      {{lesson.student}} 
    </a>
    has a(n) {{lesson.subject}} lesson on {{lesson.lessonDate.strftime('%m-%d-%Y')}}
    <!-- To <a class="btn btn-primary" href="{{ url_for('lessons.lesson', lesson_id=lesson.id) }}">
     {{lesson.title}} -->
    </a>

  
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal{{lesson.id}}">
        Details
      </button>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal{{lesson.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" id="exampleModal{{lesson.id}}">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title" id="exampleModalLabel">{{lesson.student}}'s {{lesson.subject}} Lesson.</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <h1>{{lesson.title}}</h1>
              
              <h2>When:    {{lesson.lessonDate.strftime('%m-%d-%Y')}}</h2>
              __________________________________________________
              <p id="modal-p">
                {{lesson.content}}
              </p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <form action="{{ url_for('lessons.delete_lesson', lesson_id=lesson.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
              </form>
              <form action="{{ url_for('lessons.update', lesson_id=lesson.id) }}">
                <input class="btn btn-success" type="submit" value="Update">
              </form>
              <form action="{{ url_for('lessons.lesson',lesson_id=lesson.id) }}">
                <input class="btn btn-primary" type="submit" value="View">
              </form>
            </div>
          </div>
        </div>
      </div>
    
    </p>
  {% endfor %}
  
</main>

{% endblock %}

myapp/templates/create_lesson.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='../static/css/create_lesson.css') }}">


  <main class="shadow-lg">
    <div class="container">
      <form class="form-group" method="POST">
          {{form.hidden_tag()}}
          <div class="form-group">
            {{form.student.label(class="form-control-label")}}
            {{form.student(class="form-control form-control-lg")}}
           </div>
          <div class="form-group">
              {{form.title.label(class="form-control-label")}}
              {{form.title(class="form-control form-control-lg")}}
          </div>
          <div class="form-group">
            {{form.lessonDate.label(class="form-control-label")}}
            {{form.lessonDate(class="form-control form-control-lg")}}
          </div>
          <div class="form-group">
            {{form.subject.label(class="form-control-label")}}
            {{form.subject(class="form-control form-control-lg")}}
          </div>
          <div class="form-group">
            {{form.content.label(class="form-control-label")}}
            {{form.content(class="form-control form-control-lg content-box")}}
          </div>
        <div class="form-group">
            {{form.submit(class="btn btn-outline-info")}}
        </div>
      </form>
    </div>

  </main>
{% endblock %}

myapp/templates/create_student.html
{% extends "base.html" %}
{% block content %}
This is the create page
    <div class="container">
      <form class="form-group" method="POST">
          {{form.hidden_tag()}}

          <div class="form-group">
            {{form.name.label(class="form-control-label")}}
            {{form.name(class="form-control form-control-lg")}}
        </div>
        <div class="form-group">
            {{form.submit(class="btn btn-outline-info")}}
        </div>
      </form>
    </div>

{% endblock %}

myapp/templates/index.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='../static/css/index.css') }}">

<main>
{% if current_user.is_authenticated %}

<div id="top-part">
  <h1>Welcome Back, {{current_user.username}}</h1>
  <h2>
    <a href="{{url_for('users.lessons', username=current_user.username)}}">My Lessons</a>
  </h2>
  <h2>
   <a href="{{url_for('users.students', username=current_user.username)}}">My Students</a>
</h2>
</div>
{% else %}
<div id="top-part">
  <h1>Welcome to Learnin'! Sign in or Create an Account to Continue</h1>
  <h2>
    <a href="{{url_for('users.login')}}">Sign In</a>
  </h2>
  <h2>
   <a href="{{url_for('users.register')}}">Register</a>
  </h2>
  

  
  
  {% endif %}
</main>

{% endblock %}

myapp/templates/info.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>Info about our party!!</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit veniam nihil nostrum excepturi nulla error quaerat reprehenderit, iste ad accusamus amet nesciunt, provident laborum, voluptas molestias unde non est perferendis?</p>
    </div>
   
{% endblock %}

myapp/templates/lesson.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='../static/css/lesson.css') }}">

<main>
  <div>
    <h1>Lesson with {{lesson.student}}</h1>
    <h1>{{lesson.title}}</h1>         
    <h2>When:{{lesson.lessonDate.strftime('%m-%d-%Y')}}</h2>
    <h2>What: {{lesson.subject}}</h2>
    __________________________________________________
    <p id="modal-p">
      {{lesson.content}}
    </p>
  </div>
  <div class="lesson-footer">
    <form action="{{ url_for('lessons.delete_lesson', lesson_id=lesson.id) }}" method="POST">
      <input class="btn btn-danger" type="submit" value="Delete">
    </form>
    <form action="{{ url_for('lessons.update', lesson_id=lesson.id) }}">
      <input class="btn btn-success" type="submit" value="Update">
    </form>
   
  </div>
</main>
{% endblock %}

myapp/templates/lessons.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='../static/css/lessons.css') }}">


<main>
  <div >
    <div id="top-part">
      <h1 >All {{user.username}}'s Lessons</h1>
      <h3>
        <a href="{{url_for('users.calendar', username=current_user.username)}}">Switch To Calendar </a>  |  <a href="{{url_for('lessons.create_lesson')}}">Create Lesson</a>
      </h3>
    </div>
    <div>
      {% for lesson in lessons.items %}
      <p id="lesson-summary">
        <a href="{{ url_for('lessons.student', student_name=lesson.student) }}">
          {{lesson.student}} 
        </a>
        has a(n) {{lesson.subject}} lesson on {{lesson.lessonDate.strftime('%m-%d-%Y')}}

          <!-- Button trigger modal -->
          <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal{{lesson.id}}">
            Details
          </button>

          <!-- Modal -->
          <div class="modal fade" id="exampleModal{{lesson.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" id="exampleModal{{lesson.id}}">
              <div class="modal-content">
                <div class="modal-header">
                  <h1 class="modal-title" id="exampleModalLabel">{{lesson.student}}'s {{lesson.subject}} Lesson.</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <h1>{{lesson.title}}</h1>
                  
                  <h2>When:    {{lesson.lessonDate.strftime('%m-%d-%Y')}}</h2>
                  __________________________________________________
                  <p id="modal-p">
                    {{lesson.content}}
                  </p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <form action="{{ url_for('lessons.delete_lesson', lesson_id=lesson.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                  </form>
                  <form action="{{ url_for('lessons.update', lesson_id=lesson.id) }}">
                    <input class="btn btn-success" type="submit" value="Update">
                  </form>
                  <form action="{{ url_for('lessons.lesson',lesson_id=lesson.id) }}">
                    <input class="btn btn-primary" type="submit" value="View">
                  </form>
                </div>
              </div>
            </div>
          </div>
        
        </p>
      {% endfor %}
    
  </div>
 
  <nav aria-label="Page Navigation example" class="pag-nav">
  <div class=pagination>
    {% for page_num in lessons.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if lessons.page == page_num %}
        <li class="page-item disabled">
            <a class="page-link" href="{{url_for('users.lessons', username=current_user.username, page=page_num)}}">{{ page_num }}</a>
        </li>
      {% else %}
        <li class="page-item">
            <a class="page-link" href="{{url_for('users.lessons', username=current_user.username, page=page_num)}}">{{ page_num }}</a>
        </li>
      {% endif %}
    {% endfor %}
  </div>

</nav>
</main>
{% endblock %}

myapp/templates/login.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='../static/css/login.css') }}">
   
<main>
    <form method="POST">
        {{form.hidden_tag()}}
        {{form.email.label}}{{form.email}}<br>
        {{form.password.label}}{{form.password}}<br>
        {{form.submit(class="btn btn-outline-info")}}
    </form>
</main>
{% endblock %}

myapp/templates/register.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='../static/css/register.css') }}">

<main>
    <form method="POST">
        {{form.hidden_tag()}}
        {{form.email.label}}{{form.email}}<br>
        {{form.username.label}}{{form.username}}<br>
        {{form.password.label}}{{form.password}}<br>
        {{form.pass_confirm.label}}{{form.pass_confirm}}<br>
        {{form.submit(class="btn btn-outline-info")}}
    </form>
</main>
{% endblock %}

myapp/templates/some_students.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='../static/css/some_students.css') }}">
<main>
  <div id="top-part">
    <h1 >All {{user.username}}'s Students</h1>
  </div>
  {% for lesson in lessons.items %}
  <h2>
    <a href="{{ url_for('lessons.student', student_name=lesson.student) }}">
      - {{lesson.student}} 
    </a>
  </h2>

  {% endfor %}
  <nav aria-label="Page Navigation example" class="pag-nav">
    <div class=pagination>
      {% for page_num in lessons.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if lessons.page == page_num %}
          <li class="page-item disabled">
              <a class="page-link" href="{{url_for('users.students', username=current_user.username, page=page_num)}}">{{ page_num }}</a>
          </li>
        {% else %}
          <li class="page-item">
              <a class="page-link" href="{{url_for('users.students', username=current_user.username, page=page_num)}}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}
    </div>
  </main>
  </nav>
</main>
{% endblock %}

myapp/templates/student.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='../static/css/student.css') }}">


<main>
  <div id="top-part">
    <h1>All {{student}}'s Lessons:</h1>
  </div>
  {% for lesson in lessons.items %}
  <p>
    {{student}} has a {{lesson.subject}} lesson on {{lesson.lessonDate.strftime('%m-%d-%Y')}}
    <form action="{{ url_for('lessons.lesson',lesson_id=lesson.id) }}">
      <input class="btn btn-primary" type="submit" value="View">
    </form>
  </p>

  {% endfor %}

</main>

{% endblock %}